import {
  Laptop,
  Smartphone,
  Paintbrush,
  Database,
  ShoppingCart,
  Settings,
  GitFork,
  Briefcase,
  CheckCircle2,
  ExternalLink,
  Moon,
  Sun,
  Menu,
  X,
  ArrowUp,
  Mail,
  Phone,
  MapPin,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  Github,
  Search,
  MessageSquare,
  DollarSign,
  Calculator,
  Shield,
  FileText,
  User,
  Clock,
  Send,
  Code,
  Palette,
  Globe,
  Video,
  Users,
  Megaphone,
} from 'lucide-react';

const icons = {
  LaptopCode: Laptop,
  Smartphone: Smartphone,
  Paintbrush: Paintbrush,
  Database: Database,
  ShoppingCart: ShoppingCart,
  Cogs: Settings,
  Sitemap: GitFork,
  Briefcase: Briefcase,
  CheckCircle: CheckCircle2,
  ExternalLink: ExternalLink,
  Moon: Moon,
  Sun: Sun,
  Menu: Menu,
  X: X,
  ArrowUp: ArrowUp,
  Mail: Mail,
  Phone: Phone,
  MapPin: MapPin,
  Facebook: Facebook,
  Twitter: Twitter,
  Linkedin: Linkedin,
  Instagram: Instagram,
  Github: Github,
  Search: Search,
  MessageSquare: MessageSquare,
  DollarSign: DollarSign,
  Calculator: Calculator,
  Shield: Shield,
  FileText: FileText,
  User: User,
  Clock: Clock,
  Send: Send,
  Code: Code,
  Palette: Palette,
  Globe: Globe,
  Video: Video,
  Users: Users,
  Megaphone: Megaphone
};

export function DynamicIcon({ name, ...props }) {
  const IconComponent = icons[name] || icons.LaptopCode;
  return <IconComponent {...props} />;
}
